export const categoryResponseMock = {
  id: "MLA1055",
  name: "Celulares y Smartphones",
  picture:
    "http://resources.mlstatic.com/category/images/fdca1620-3b63-4af2-bc0b-aeed17048d5d.png",
  permalink: null,
  total_items_in_this_category: 81335,
  path_from_root: [
    {
      id: "MLA1051",
      name: "Celulares y Teléfonos",
    },
    {
      id: "MLA1055",
      name: "Celulares y Smartphones",
    },
  ],
  children_categories: [],
  attribute_types: "variations",
  settings: {
    adult_content: false,
    buying_allowed: true,
    buying_modes: ["buy_it_now", "auction"],
    catalog_domain: "MLA-CELLPHONES",
    coverage_areas: "not_allowed",
    currencies: ["ARS"],
    fragile: false,
    immediate_payment: "required",
    item_conditions: ["not_specified", "used", "new"],
    items_reviews_allowed: false,
    listing_allowed: true,
    max_description_length: 50000,
    max_pictures_per_item: 12,
    max_pictures_per_item_var: 10,
    max_sub_title_length: 70,
    max_title_length: 60,
    maximum_price: null,
    minimum_price: 33,
    mirror_category: null,
    mirror_master_category: null,
    mirror_slave_categories: [],
    price: "required",
    reservation_allowed: "not_allowed",
    restrictions: [],
    rounded_address: false,
    seller_contact: "not_allowed",
    shipping_modes: ["me1", "custom", "me2", "not_specified"],
    shipping_options: ["custom", "carrier"],
    shipping_profile: "optional",
    show_contact_information: false,
    simple_shipping: "optional",
    stock: "required",
    sub_vertical: "smartphones",
    subscribable: false,
    tags: [],
    vertical: "consumer_electronics",
    vip_subdomain: "articulo",
    buyer_protection_programs: ["delivered", "undelivered"],
    status: "enabled",
  },
  channels_settings: [],
  meta_categ_id: null,
  attributable: false,
  date_created: "2018-04-25T08:12:56.000Z",
};
export const categoriesResponseMock = [
  "Celulares y Smartphones",
  "Celulares y Smartphones",
  "Celulares y Smartphones",
];
export const emptyCategoryResponseMock = null;
