export const itemsResponseMock = {
  site_id: "MLA",
  query: "iphone",
  paging: {
    total: 21950,
    primary_results: 1000,
    offset: 0,
    limit: 50,
  },
  results: [
    {
      id: "MLA916044386",
      site_id: "MLA",
      title: "iPhone 11 64 Gb Blanco",
      seller: {
        id: 6673807,
        permalink: "http://perfil.mercadolibre.com.ar/IDENTIKITNET",
        registration_date: "2007-03-21T12:29:03.000-04:00",
        car_dealer: false,
        real_estate_agency: false,
        tags: [
          "normal",
          "user_info_verified",
          "credits_profile",
          "messages_as_seller",
          "messages_as_buyer",
        ],
        seller_reputation: {
          transactions: {
            total: 23,
            canceled: 3,
            period: "historic",
            ratings: {
              negative: 0,
              positive: 1,
              neutral: 0,
            },
            completed: 20,
          },
          power_seller_status: null,
          metrics: {
            claims: {
              rate: 0,
              value: 1,
              period: "365 days",
            },
            delayed_handling_time: {
              rate: 0.1,
              value: 2,
              period: "365 days",
            },
            sales: {
              period: "365 days",
              completed: 20,
            },
            cancellations: {
              rate: 0,
              value: 0,
              period: "365 days",
            },
          },
          level_id: "5_green",
        },
      },
      price: 134990,
      prices: {
        id: "MLA916044386",
        prices: [
          {
            id: "1",
            type: "standard",
            conditions: {
              context_restrictions: [],
              start_time: null,
              end_time: null,
              eligible: true,
            },
            amount: 134990,
            regular_amount: null,
            currency_id: "ARS",
            exchange_rate_context: "DEFAULT",
            metadata: {},
            last_updated: "2021-04-13T18:43:10Z",
          },
        ],
        presentation: {
          display_currency: "ARS",
        },
        payment_method_prices: [],
        reference_prices: [],
        purchase_discounts: [],
      },
      sale_price: null,
      currency_id: "ARS",
      available_quantity: 1,
      sold_quantity: 0,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2041-04-08T04:00:00.000Z",
      condition: "new",
      permalink:
        "https://www.mercadolibre.com.ar/iphone-11-64-gb-blanco/p/MLA15149562",
      thumbnail:
        "http://http2.mlstatic.com/D_641268-MLA43654417348_102020-I.jpg",
      thumbnail_id: "641268-MLA43654417348_102020",
      accepts_mercadopago: true,
      installments: {
        quantity: 12,
        amount: 19142.71,
        rate: 70.17,
        currency_id: "ARS",
      },
      address: {
        state_id: "AR-R",
        state_name: "Río Negro",
        city_id: null,
        city_name: "El Bolsón",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["mandatory_free_shipping"],
        logistic_type: "drop_off",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "AR",
          name: "Argentina",
        },
        state: {
          id: "AR-R",
          name: "Río Negro",
        },
        city: {
          id: null,
          name: "El Bolsón",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "BRAND",
          name: "Marca",
          value_id: "9344",
          value_name: "Apple",
          attribute_group_name: "Otros",
          source: 1,
          value_struct: null,
          values: [
            {
              id: "9344",
              name: "Apple",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
        },
        {
          id: "GPU_MODEL",
          name: "Modelo de GPU",
          value_name: "Apple GPU MP4",
          value_struct: null,
          source: 1,
          value_id: "7740544",
          values: [
            {
              name: "Apple GPU MP4",
              struct: null,
              source: 1,
              id: "7740544",
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
        },
        {
          name: "Condición del ítem",
          value_id: "2230284",
          value_struct: null,
          source: 3045741222775799,
          id: "ITEM_CONDITION",
          values: [
            {
              name: "Nuevo",
              struct: null,
              source: 3045741222775799,
              id: "2230284",
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          value_name: "Nuevo",
        },
        {
          value_struct: null,
          values: [
            {
              id: "58993",
              name: "iPhone",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          id: "LINE",
          name: "Línea",
          value_name: "iPhone",
          value_id: "58993",
          attribute_group_name: "Otros",
        },
        {
          value_id: "7739079",
          attribute_group_name: "Otros",
          source: 1,
          id: "MODEL",
          name: "Modelo",
          value_name: "iPhone 11",
          value_struct: null,
          values: [
            {
              struct: null,
              source: 1,
              id: "7739079",
              name: "iPhone 11",
            },
          ],
          attribute_group_id: "OTHERS",
        },
        {
          id: "PROCESSOR_MODEL",
          name: "Modelo del procesador",
          attribute_group_name: "Otros",
          value_id: "7740540",
          value_name: "Apple A13 Bionic",
          value_struct: null,
          values: [
            {
              id: "7740540",
              name: "Apple A13 Bionic",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
        },
        {
          name: "Peso",
          value_struct: {
            number: 194,
            unit: "g",
          },
          attribute_group_id: "OTHERS",
          id: "WEIGHT",
          value_id: "2583040",
          value_name: "194 g",
          values: [
            {
              id: "2583040",
              name: "194 g",
              struct: {
                number: 194,
                unit: "g",
              },
              source: 1,
            },
          ],
          attribute_group_name: "Otros",
          source: 1,
        },
      ],
      original_price: null,
      category_id: "MLA1055",
      official_store_id: null,
      domain_id: "MLA-CELLPHONES",
      catalog_product_id: "MLA15149562",
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller_candidate",
      ],
      catalog_listing: true,
      use_thumbnail_id: true,
      order_backend: 1,
    },
    {
      id: "MLA913236423",
      site_id: "MLA",
      title: "iPhone 11 128 Gb Negro",
      seller: {
        id: 86356879,
        permalink: "http://perfil.mercadolibre.com.ar/INFLABLESWORLD",
        registration_date: "2005-10-14T18:37:11.000-04:00",
        car_dealer: false,
        real_estate_agency: false,
        tags: [
          "normal",
          "user_info_verified",
          "eshop",
          "mshops",
          "messages_as_seller",
          "messages_as_buyer",
        ],
        eshop: {
          nick_name: "INFLABLESWORLD",
          eshop_rubro: null,
          eshop_id: 127430,
          eshop_locations: [],
          site_id: "MLA",
          eshop_logo_url: "http://resources.mlstatic.com/eshops/86356879.jpg",
          eshop_status_id: 2,
          seller: 86356879,
          eshop_experience: 0,
        },
        seller_reputation: {
          transactions: {
            total: 68079,
            canceled: 3506,
            period: "historic",
            ratings: {
              negative: 0.03,
              positive: 0.95,
              neutral: 0.02,
            },
            completed: 64573,
          },
          power_seller_status: "platinum",
          metrics: {
            claims: {
              rate: 0.0163,
              value: 87,
              period: "60 days",
            },
            delayed_handling_time: {
              rate: 0.0077,
              value: 36,
              period: "60 days",
            },
            sales: {
              period: "60 days",
              completed: 5055,
            },
            cancellations: {
              rate: 0.0078,
              value: 42,
              period: "60 days",
            },
          },
          level_id: "5_green",
        },
      },
      price: 152999,
      prices: {
        id: "MLA913236423",
        prices: [
          {
            id: "7",
            type: "standard",
            conditions: {
              context_restrictions: [],
              start_time: null,
              end_time: null,
              eligible: true,
            },
            amount: 152999,
            regular_amount: null,
            currency_id: "ARS",
            exchange_rate_context: "DEFAULT",
            metadata: {},
            last_updated: "2021-04-15T15:55:37Z",
          },
        ],
        presentation: {
          display_currency: "ARS",
        },
        payment_method_prices: [],
        reference_prices: [],
        purchase_discounts: [],
      },
      sale_price: null,
      currency_id: "ARS",
      available_quantity: 1,
      sold_quantity: 4,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2041-03-18T04:00:00.000Z",
      condition: "new",
      permalink:
        "https://www.mercadolibre.com.ar/iphone-11-128-gb-negro/p/MLA15149567",
      thumbnail:
        "http://http2.mlstatic.com/D_738648-MLA43654417399_102020-I.jpg",
      thumbnail_id: "738648-MLA43654417399_102020",
      accepts_mercadopago: true,
      installments: {
        quantity: 12,
        amount: 21696.53,
        rate: 70.17,
        currency_id: "ARS",
      },
      address: {
        state_id: "AR-B",
        state_name: "Buenos Aires",
        city_id: null,
        city_name: "Villa Lynch",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["self_service_in", "mandatory_free_shipping"],
        logistic_type: "cross_docking",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "AR",
          name: "Argentina",
        },
        state: {
          id: "AR-B",
          name: "Buenos Aires",
        },
        city: {
          id: null,
          name: "Villa Lynch",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          value_id: "9344",
          value_name: "Apple",
          value_struct: null,
          values: [
            {
              struct: null,
              source: 1,
              id: "9344",
              name: "Apple",
            },
          ],
          source: 1,
          name: "Marca",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          id: "BRAND",
        },
        {
          name: "Modelo de GPU",
          value_id: "7740544",
          values: [
            {
              id: "7740544",
              name: "Apple GPU MP4",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          id: "GPU_MODEL",
          value_name: "Apple GPU MP4",
          value_struct: null,
          attribute_group_name: "Otros",
        },
        {
          value_id: "2230284",
          value_struct: null,
          attribute_group_name: "Otros",
          id: "ITEM_CONDITION",
          name: "Condición del ítem",
          value_name: "Nuevo",
          values: [
            {
              name: "Nuevo",
              struct: null,
              source: 3045741222775799,
              id: "2230284",
            },
          ],
          attribute_group_id: "OTHERS",
          source: 3045741222775799,
        },
        {
          value_struct: null,
          attribute_group_id: "OTHERS",
          value_id: "58993",
          value_name: "iPhone",
          values: [
            {
              id: "58993",
              name: "iPhone",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_name: "Otros",
          source: 1,
          id: "LINE",
          name: "Línea",
        },
        {
          id: "MODEL",
          attribute_group_name: "Otros",
          source: 1,
          name: "Modelo",
          value_id: "7739079",
          value_name: "iPhone 11",
          value_struct: null,
          values: [
            {
              id: "7739079",
              name: "iPhone 11",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
        },
        {
          name: "Modelo del procesador",
          value_name: "Apple A13 Bionic",
          values: [
            {
              name: "Apple A13 Bionic",
              struct: null,
              source: 1,
              id: "7740540",
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          id: "PROCESSOR_MODEL",
          value_struct: null,
          source: 1,
          value_id: "7740540",
        },
        {
          value_name: "194 g",
          attribute_group_name: "Otros",
          source: 1,
          name: "Peso",
          value_id: "2583040",
          values: [
            {
              name: "194 g",
              struct: {
                number: 194,
                unit: "g",
              },
              source: 1,
              id: "2583040",
            },
          ],
          attribute_group_id: "OTHERS",
          id: "WEIGHT",
          value_struct: {
            number: 194,
            unit: "g",
          },
        },
      ],
      original_price: null,
      category_id: "MLA1055",
      official_store_id: null,
      domain_id: "MLA-CELLPHONES",
      catalog_product_id: "MLA15149567",
      tags: [
        "loyalty_discount_eligible",
        "good_quality_picture",
        "good_quality_thumbnail",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller_candidate",
      ],
      catalog_listing: true,
      use_thumbnail_id: true,
      order_backend: 2,
    },
    {
      id: "MLA907279808",
      site_id: "MLA",
      title: " iPhone SE (2nd Generation) 64 Gb (product)red",
      seller: {
        id: 9096361,
        permalink: "http://perfil.mercadolibre.com.ar/FLXWW",
        registration_date: "2002-04-22T00:00:00.000-04:00",
        car_dealer: false,
        real_estate_agency: false,
        tags: [
          "normal",
          "user_info_verified",
          "credits_profile",
          "messages_as_seller",
          "messages_as_buyer",
        ],
        seller_reputation: {
          transactions: {
            total: 255,
            canceled: 20,
            period: "historic",
            ratings: {
              negative: 0.11,
              positive: 0.89,
              neutral: 0,
            },
            completed: 235,
          },
          power_seller_status: "silver",
          metrics: {
            claims: {
              rate: 0,
              excluded: {
                real_rate: 0,
                real_value: 1,
              },
              value: 0,
              period: "60 days",
            },
            delayed_handling_time: {
              rate: 0,
              excluded: {
                real_rate: 0.1752,
                real_value: 17,
              },
              value: 0,
              period: "60 days",
            },
            sales: {
              period: "60 days",
              completed: 106,
            },
            cancellations: {
              rate: 0,
              excluded: {
                real_rate: 0,
                real_value: 0,
              },
              value: 0,
              period: "60 days",
            },
          },
          protection_end_date: "2021-04-22T00:00:00.000-04:00",
          real_level: "yellow",
          level_id: "5_green",
        },
      },
      price: 90999,
      prices: {
        id: "MLA907279808",
        prices: [
          {
            id: "3",
            type: "standard",
            conditions: {
              context_restrictions: [],
              start_time: null,
              end_time: null,
              eligible: true,
            },
            amount: 90999,
            regular_amount: null,
            currency_id: "ARS",
            exchange_rate_context: "DEFAULT",
            metadata: {},
            last_updated: "2021-04-14T20:53:41Z",
          },
        ],
        presentation: {
          display_currency: "ARS",
        },
        payment_method_prices: [],
        reference_prices: [],
        purchase_discounts: [],
      },
      sale_price: null,
      currency_id: "ARS",
      available_quantity: 10,
      sold_quantity: 0,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2041-01-31T04:00:00.000Z",
      condition: "new",
      permalink:
        "https://www.mercadolibre.com.ar/iphone-se-2nd-generation-64-gb-productred/p/MLA15591333",
      thumbnail:
        "http://http2.mlstatic.com/D_977517-MLA42321073074_062020-I.jpg",
      thumbnail_id: "977517-MLA42321073074_062020",
      accepts_mercadopago: true,
      installments: {
        quantity: 12,
        amount: 12904.42,
        rate: 70.17,
        currency_id: "ARS",
      },
      address: {
        state_id: "AR-B",
        state_name: "Buenos Aires",
        city_id: null,
        city_name: "La Plata",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["mandatory_free_shipping"],
        logistic_type: "drop_off",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "AR",
          name: "Argentina",
        },
        state: {
          id: "AR-B",
          name: "Buenos Aires",
        },
        city: {
          id: null,
          name: "La Plata",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          values: [
            {
              id: "9344",
              name: "Apple",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_name: "Otros",
          source: 1,
          value_id: "9344",
          name: "Marca",
          value_name: "Apple",
          value_struct: null,
          attribute_group_id: "OTHERS",
          id: "BRAND",
        },
        {
          value_name: "Apple GPU",
          attribute_group_name: "Otros",
          source: 1,
          attribute_group_id: "OTHERS",
          id: "GPU_MODEL",
          name: "Modelo de GPU",
          value_id: "7741027",
          value_struct: null,
          values: [
            {
              struct: null,
              source: 1,
              id: "7741027",
              name: "Apple GPU",
            },
          ],
        },
        {
          value_id: "2230284",
          value_name: "Nuevo",
          values: [
            {
              struct: null,
              source: 2860837171021627,
              id: "2230284",
              name: "Nuevo",
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          source: 2860837171021627,
          name: "Condición del ítem",
          value_struct: null,
          id: "ITEM_CONDITION",
        },
        {
          id: "LINE",
          name: "Línea",
          value_struct: null,
          values: [
            {
              id: "58993",
              name: "iPhone",
              struct: null,
              source: 1,
            },
          ],
          source: 1,
          value_id: "58993",
          value_name: "iPhone",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
        },
        {
          values: [
            {
              struct: null,
              source: 1,
              id: "8230322",
              name: "iPhone SE (2nd Generation)",
            },
          ],
          id: "MODEL",
          value_struct: null,
          value_name: "iPhone SE (2nd Generation)",
          attribute_group_id: "OTHERS",
          attribute_group_name: "Otros",
          source: 1,
          name: "Modelo",
          value_id: "8230322",
        },
        {
          value_id: "7740540",
          value_struct: null,
          values: [
            {
              name: "Apple A13 Bionic",
              struct: null,
              source: 1,
              id: "7740540",
            },
          ],
          id: "PROCESSOR_MODEL",
          name: "Modelo del procesador",
          attribute_group_name: "Otros",
          source: 1,
          value_name: "Apple A13 Bionic",
          attribute_group_id: "OTHERS",
        },
        {
          value_name: "148 g",
          values: [
            {
              name: "148 g",
              struct: {
                number: 148,
                unit: "g",
              },
              source: 1,
              id: "6861161",
            },
          ],
          attribute_group_id: "OTHERS",
          id: "WEIGHT",
          value_id: "6861161",
          value_struct: {
            number: 148,
            unit: "g",
          },
          attribute_group_name: "Otros",
          source: 1,
          name: "Peso",
        },
      ],
      original_price: null,
      category_id: "MLA1055",
      official_store_id: null,
      domain_id: "MLA-CELLPHONES",
      catalog_product_id: "MLA15591333",
      tags: [
        "brand_verified",
        "extended_warranty_eligible",
        "good_quality_picture",
        "loyalty_discount_eligible",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller_candidate",
      ],
      catalog_listing: true,
      use_thumbnail_id: true,
      order_backend: 3,
    },
  ],
};
export const emptyItemsResponseMock = {
  ...itemsResponseMock,
  results: [],
};
